version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.3
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
      AIRFLOW__CORE__FERNET_KEY: your_fernet_key_here
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_app:/opt/airflow/spark_app
    ports:
      - "8080:8080"
    command: webserver

  airflow_scheduler:
    image: apache/airflow:2.7.3
    depends_on:
      - airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark_app:/opt/airflow/spark_app
    command: scheduler

  spark:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark_app:/opt/spark_app
    command: bash -c "while true; do sleep 30; done"

volumes:
  pgdata:
